Add TLS 1.2 support for Windows PowerShell
EncoreTechnologies/puppet-powershellmodule pull request #7
Opened 2020-04-25 12:22 UTC by pauby

Adds TLS 1.2 support for Windows PowerShell to allow using PowerShell Gallery. PowerShell Core already support TLS 1.2 so shouldn't have to specifically add it.

Fixes #6

2020-04-28 14:02 UTC, nmaludy requested changes
This change looks great! Could you please add an entry into the Changelog so we let others know this is fixed and also give you proper credit for the fix?

Thanks for this!

2020-04-28 15:21 UTC, gsperry2011 approved these changes
Added a few comments for the future when we might move away from tls1.2 - Tested code on both 2016 and 2019 powershell version 5.1

2020-04-28 15:42 UTC, nmaludy approved these changes
LGTM, i'll add changelog later.

2020-04-28 15:42 UTC, merged

2020-05-10 13:20 UTC, pauby commented
@nmaludy Apologies I've just seen this and your request to add to the Changelog.